AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AI Curated Newsletter - MVP

Globals:
  Function:
    Timeout: 900
    MemorySize: 1024
    Runtime: python3.14
    Architectures:
      - x86_64

Parameters:
  FromEmail:
    Type: String
    Description: Sender email address (must be verified in SES)
    Default: noreply@example.com

  ToEmail:
    Type: String
    Description: Recipient email address
    Default: recipient@example.com

Resources:
  # Lambda Function
  NewsletterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ai-curated-newsletter
      CodeUri: .
      Handler: src.handler.lambda_handler
      Environment:
        Variables:
          CACHE_TABLE_NAME: !Ref CacheTable
          HISTORY_TABLE_NAME: !Ref HistoryTable
          SOURCES_CONFIG_PATH: config/sources.yaml
          FROM_EMAIL: !Ref FromEmail
          TO_EMAIL: !Ref ToEmail
          BEDROCK_MODEL_ID: anthropic.claude-haiku-4-5-20251001-v1:0
          BEDROCK_INFERENCE_PROFILE_ARN: !Sub 'arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:inference-profile/jp.anthropic.claude-haiku-4-5-20251001-v1:0'
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CacheTable
        - DynamoDBCrudPolicy:
            TableName: !Ref HistoryTable
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource:
                - !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-haiku-4-5*'
                - !Sub 'arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:inference-profile/*anthropic.claude-haiku-4-5*'
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: '*'
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 0 * * ? *)  # 毎日JST 09:00 (UTC 00:00)
            Description: 毎日JST 09:00にニュースレターを実行
            Enabled: true

  # DynamoDB Cache Table
  CacheTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ai-curated-newsletter-cache
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      Tags:
        - Key: Application
          Value: ai-curated-newsletter

  # DynamoDB History Table
  HistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ai-curated-newsletter-history
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Application
          Value: ai-curated-newsletter

Outputs:
  NewsletterFunction:
    Description: Newsletter Lambda Function ARN
    Value: !GetAtt NewsletterFunction.Arn

  NewsletterFunctionIamRole:
    Description: Implicit IAM Role created for Newsletter function
    Value: !GetAtt NewsletterFunctionRole.Arn

  CacheTableName:
    Description: DynamoDB Cache Table Name
    Value: !Ref CacheTable

  HistoryTableName:
    Description: DynamoDB History Table Name
    Value: !Ref HistoryTable
